//
//  MainWorkerTests.swift
//  TestCleanSwift
//
//  Created by Tanasak.Nge on 12/6/2561 BE.
//  Copyright (c) 2561 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TestCleanSwift
import XCTest

class MainWorkerTests: XCTestCase
{
  // MARK: Subject under test
  private let timeout: TimeInterval = 15.0

  var sut: MainWorker!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupMainWorker()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupMainWorker()
  {
    sut = MainWorker()
  }
  
  // MARK: Test doubles
  
  // MARK: Tests
  
  func testFetchList() {
    let expectation = self.expectation(description: "Wait for fetchList() to return")
    sut.fetchList(page: "1") { (result) in
      switch result {
      case .success(_):
        expectation.fulfill()
      case .failure(let error):
        XCTFail(error.localizedDescription)
      }
    }
    waitForExpectations(timeout: timeout, handler: nil)
  }
  
}
