//
//  MainRouter.swift
//  TestCleanSwift
//
//  Created by Tanasak.Nge on 25/5/2561 BE.
//  Copyright (c) 2561 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainRoutingLogic
{
  func navigateToInfo(movie: Main.Something.ViewModel.Movie)
}

protocol MainDataPassing
{
  var dataStore: MainDataStore? { get }
}

class MainRouter: NSObject, MainRoutingLogic, MainDataPassing
{
    
  weak var viewController: MainViewController?
  var dataStore: MainDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
 
  func navigateToInfo(movie: Main.Something.ViewModel.Movie) {
    let destinationVC = InfoViewController()
    var destinationDS = destinationVC.router?.dataStore
    passDataToInfoVC(source: dataStore!, destination: &destinationDS!)
    viewController?.show(destinationVC, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToInfoVC(source: MainDataStore, destination: inout InfoDataStore)
  {
    if let selectedRow = viewController?.tableView.indexPathForSelectedRow?.row {
      destination.movie = source.movieList?.movies[selectedRow]
    }
  }
}
