//
//  MainPresenter.swift
//  TestCleanSwift
//
//  Created by Tanasak.Nge on 25/5/2561 BE.
//  Copyright (c) 2561 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic
{
  func presentSomething(response: Main.Something.Response)
}

class MainPresenter: MainPresentationLogic
{
  weak var viewController: MainDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Main.Something.Response)
  {
    var viewModel: Main.Something.ViewModel = Main.Something.ViewModel(movieList: [])
    response.movieList.movies.forEach{
      let posterPath = "https://image.tmdb.org/t/p/w200\($0.posterPath)"
      let rating     = "Rating: \($0.voteAverage)/10"
      let movie = Main.Something.ViewModel.Movie(movieTitle: $0.title,
                                                 movieRating: rating,
                                                 moviePosterPath: posterPath)
      viewModel.movieList.append(movie)
    }
    viewController?.displayFetchList(viewModel: viewModel)
  }
}
