//
//  MainModels.swift
//  TestCleanSwift
//
//  Created by Tanasak.Nge on 25/5/2561 BE.
//  Copyright (c) 2561 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Main {
  // MARK: Use cases
  
  enum Something {
    struct Request {
      var loadingIndicator: Bool
    }
    struct Response {
      var movieList: MovieList
      var validateError: [validateError]?
      struct validateError {
        var validateErrorIndex: Int?
        var validateErrorMessage: String?
      }
      init(movieList: MovieList,
           validateError: [validateError]? = nil) {
        self.movieList = movieList
        self.validateError = validateError
      }
    }
    struct Error {
      var errorMessage: String
    }
    struct ViewModel {
      struct Movie: Equatable {
        let movieTitle: String
        let movieRating: String
        let moviePosterPath: String
        var movieInputErrorMessage: String?
        init(movieTitle: String,
             movieRating: String,
             moviePosterPath: String,
             movieInputErrorMessage: String? = nil) {
          self.movieTitle = movieTitle
          self.movieRating = movieRating
          self.moviePosterPath = moviePosterPath
          self.movieInputErrorMessage = movieInputErrorMessage
        }
      }
      var movieList: [Movie]
    }
  }
}
