//
//  MainPresenter.swift
//  TestCleanSwift
//
//  Created by Tanasak.Nge on 25/5/2561 BE.
//  Copyright (c) 2561 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic: BasePresenterLogic {
  func presentMovieList(response: Main.Something.Response)
  func presentErrorMessage(error: Main.Something.Error)

}

class MainPresenter: BasePresenter, MainPresentationLogic {

  weak var viewController: MainDisplayLogic? {
    didSet{
      baseViewController = viewController
    }
  }
  
  // MARK: Do something
  
  func presentMovieList(response: Main.Something.Response) {
    
    var viewModel: Main.Something.ViewModel = Main.Something.ViewModel(movieList: [])
    response.movieList.movies.forEach{
      let posterPath = APIs.downloadImage.loadImage(withSize: .thumbnail, withPath: $0.posterPath)
      let rating     = "Rating: \($0.voteAverage)/10"
      let movie = Main.Something.ViewModel.Movie(movieTitle: $0.name,
                                                 movieRating: rating,
                                                 moviePosterPath: posterPath)
      viewModel.movieList.append(movie)
    }
    hideLoading()
    viewController?.displayFetchList(viewModel: viewModel)
  }

  func presentErrorMessage(error: Main.Something.Error) {
    hideLoading()
    viewController?.displayError(title: "Error", message: error.error.localizedDescription)
  }
}
