//
//  MainInteractor.swift
//  TestCleanSwift
//
//  Created by Tanasak.Nge on 25/5/2561 BE.
//  Copyright (c) 2561 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic
{
  func fetchMovie(withLoadingIndicator: Bool)
}

protocol MainDataStore
{
  //var name: String { get set }
  var movieList: MovieList? { get }
}

class MainInteractor: MainBusinessLogic, MainDataStore
{
  var movieList: MovieList?
  
  var presenter: MainPresentationLogic?
  var worker = MainWorker()
  
  // MARK: Do something
  
  func fetchMovie(withLoadingIndicator: Bool) {
    withLoadingIndicator ? presenter?.showLoading() : nil
    worker.doSomeWork { (result) in
      switch result {
      case .success(let value):
        self.movieList = value
        let response = Main.Something.Response(movieList: value)
        self.presenter?.presentSomething(response: response)
      case .failure(let error):
        self.presenter?.presentErrorMessage(error: Main.Something.Error(error: error.errorObject))
      }
    }
  }
}

