//
//  MainWorker.swift
//  TestCleanSwift
//
//  Created by Tanasak.Nge on 25/5/2561 BE.
//  Copyright (c) 2561 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MainWorker {
  func fetchList(page: String, completion: @escaping (Result<(MovieList)>) -> Void) {

    let request = Request(endpoint: FetchMovieEndPoint.FetchMovieList(page: page))

    HTTPClient.shared.executeRequest(request: request) { (result: Result<MovieList>) in
      completion(result)
    }


//    let requestURL = APIs.fetchSeriesList.fectchSeries(withPage: page)


//    NetworkClient.request(url: requestURL,
//                          params: nil,
//                          paramsType: MovieList.self,
//                          method: HTTPMethod.get,
//                          headers: nil,
//                          resultType: MovieList.self) { (result) in
//                            DispatchQueue.main.async {
//                              completion(NetworkBaseService.transformServiceResponse(result))
//                            }
//    }
  }

  static func testPost() {
    let request = Request(endpoint: FetchMovieEndPoint.testPost(name: "Yo!", job: "iOS"))
    HTTPClient.shared.executeRequest(request: request) { (result: Result<testPostModel>) in

    }
  }
}

