//
//  MainInteractor.swift
//  TestCleanSwift
//
//  Created by Tanasak.Nge on 25/5/2561 BE.
//  Copyright (c) 2561 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic
{
  func fetchMovie()
}

protocol MainDataStore
{
  //var name: String { get set }
  var movieList: MovieList? { get }
}

class MainInteractor: MainBusinessLogic, MainDataStore
{
  var movieList: MovieList?
  
  var presenter: MainPresentationLogic?
  var worker = MainWorker()
  //var name: String = ""
  
  // MARK: Do something
  
  func fetchMovie() {
    worker.doSomeWork { (result) in
      self.movieList = result
      let response = Main.Something.Response(movieList: result)
      self.presenter?.presentSomething(response: response)
    }
  }
}

