# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Test -> Build"
  lane :Debug do
    tests
	build   
  end

  desc "Testing lane (clean before test)"
  lane :tests do
  	run_tests(
  		workspace: "TestCleanSwift.xcworkspace",
  		scheme: "TestCleanSwift",
  		clean: true,
  		devices: "iPhone X"
	)
  end

  desc "Building lane (clean before build)"
  lane :build do
	  get_certificates           # invokes cert
  	  get_provisioning_profile   # invokes sigh
	  build_ios_app(
	  workspace: "TestCleanSwift.xcworkspace",
	  configuration: "Debug",
	  scheme: "TestCleanSwift",
	  silent: true,
	  clean: true
	)
  end
end
