//
//  InfoInteractor.swift
//  TestCleanSwift
//
//  Created by Tanasak.Nge on 28/5/2561 BE.
//  Copyright (c) 2561 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InfoBusinessLogic
{
  func doSomething(request: Info.Something.Request)
  func showMovieDetail()
}

protocol InfoDataStore
{
  var movie: Movie! { get set }
}

class InfoInteractor: InfoBusinessLogic, InfoDataStore
{
  var movie: Movie!
  
  var presenter: InfoPresentationLogic?
  var worker: InfoWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Info.Something.Request)
  {
//    worker = InfoWorker()
//    worker?.doSomeWork()
//
//    let response = Info.Something.Response()
//    presenter?.presentSomething(response: response)
  }
  
  func showMovieDetail() {
    presenter?.presentMovie(response: Info.Something.Response(movie: movie))
  }
}
