//
//  InfoPresenter.swift
//  TestCleanSwift
//
//  Created by Tanasak.Nge on 28/5/2561 BE.
//  Copyright (c) 2561 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InfoPresentationLogic
{
  func presentSomething(response: Info.Something.Response)
  func presentMovie(response: Info.Something.Response)
}

class InfoPresenter: InfoPresentationLogic
{
  
  

  weak var viewController: InfoDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Info.Something.Response)
  {
//    let viewModel = Info.Something.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
  }
  
  func presentMovie(response: Info.Something.Response) {
    let viewModel = Info.Something.ViewModel(movieName: response.movie.title)
    viewController?.displayMovieName(viewModel: viewModel)
  }
  
}
