//
//  InfoWorker.swift
//  TestCleanSwift
//
//  Created by Tanasak.Nge on 28/5/2561 BE.
//  Copyright (c) 2561 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import NilNetzwerk

class InfoWorker
{
    func fetchTrailer(movieId: Int, completion: @escaping (Result<(TrailerList)>) -> Void) {
        let request = Request(endpoint: FetchMovieEndPoint.GetMovieTrailer(movieId: String(movieId)))
        NetworkClient.shared.executeRequest(request: request) { (result: Result<TrailerList>) in
            completion(result)
        }
    }
}
