//
//  InfoWorker.swift
//  TestCleanSwift
//
//  Created by Tanasak.Nge on 28/5/2561 BE.
//  Copyright (c) 2561 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import NilNetzwerk

class InfoWorker
{
//    func fetchTrailer(id: Int, completion: @escaping (Result<(MovieList)>) -> Void) {
//        let request = Request(endpoint: FetchMovieEndPoint.FetchMovieList(page: page))
//        NetworkClient.shared.executeRequest(request: request) { (result: Result<MovieList>) in
//            completion(result)
//        }
//    }
}
