//
//  InfoModels.swift
//  TestCleanSwift
//
//  Created by Tanasak.Nge on 28/5/2561 BE.
//  Copyright (c) 2561 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Info {
    // MARK: Use cases

    enum Something {
        struct Request {
        }
        struct Response {
            let movie: Movie
            let movieTrailers: TrailerList?
        }
        struct ViewModel {
            struct Movie {
                let movieTitle: String
                let movieRating: String
                let moviePosterPath: String
                let movieOverview: String
                let movieTrailerLink: String?
            }
            let movie: Movie
        }
    }
}
